"""add instructor fields

Revision ID: 0eb4a8b6b715
Revises: 6133a336641e
Create Date: 2019-03-22 00:50:57.106853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0eb4a8b6b715'
down_revision = '6133a336641e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('instructor', 
                  sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('instructor', 
                  sa.Column('perfered_office_hours', sa.String(length=256), 
                            nullable=True))
    op.add_column('instructor', 
                  sa.Column('updated', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('instructor', 'updated')
    op.drop_column('instructor', 'perfered_office_hours')
    op.drop_column('instructor', 'created')

    # ### end Alembic commands ###
