"""added user fields

Revision ID: 18039f8adcbb
Revises: c68d32b90c8d
Create Date: 2019-03-21 23:28:44.150730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18039f8adcbb'
down_revision = 'c68d32b90c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('permission', sa.Enum('admin', 'instructor'), nullable=False))
    op.add_column('user', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated')
    op.drop_column('user', 'permission')
    op.drop_column('user', 'created')
    # ### end Alembic commands ###
