"""create syllabus instructor association obj

Revision ID: 1e93571e66b0
Revises: c14f264c92ba
Create Date: 2019-03-31 19:38:00.347070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e93571e66b0'
down_revision = 'c14f264c92ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'syllabus_instructor',
        sa.Column('syllabus_section', sa.Integer(), nullable=False),
        sa.Column('syllabus_semester', sa.Enum('spring', 'summer', 'fall'), 
                  nullable=False),
        sa.Column('syllabus_year', sa.Integer(), nullable=False),
        sa.Column('syllabus_version', sa.Integer(), nullable=False),
        sa.Column('syllabus_course_number', sa.Integer(), nullable=False),
        sa.Column('syllabus_course_version', sa.Integer(), nullable=False),
        sa.Column('instructor_id', sa.Integer(), nullable=False),
        sa.Column('job_on_syllabus', sa.String(length=120), nullable=True),
        
        sa.PrimaryKeyConstraint('syllabus_section', 
                                'syllabus_semester', 
                                'syllabus_year', 
                                'syllabus_version', 
                                'syllabus_course_number', 
                                'syllabus_course_version', 
                                'instructor_id'),
        
        sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], ),

        sa.ForeignKeyConstraint(
            [
                'syllabus_section', 
                'syllabus_semester', 
                'syllabus_year', 
                'syllabus_version', 
                'syllabus_course_number', 
                'syllabus_course_version',
            ], 
            [
                'syllabus.section', 
                'syllabus.semester', 
                'syllabus.year', 
                'syllabus.version', 
                'syllabus.course_number', 
                'syllabus.course_version',
            ]))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('syllabus_instructor')
    # ### end Alembic commands ###
