"""add admin user

Revision ID: 3539d79a1c0b
Revises: be1c8e33b37e
Create Date: 2019-04-15 22:16:24.544765

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash
#from sqlalchemy.orm.session import Session
#from ..app.models import User

# revision identifiers, used by Alembic.
revision = '3539d79a1c0b'
down_revision = 'be1c8e33b37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    password_hash = generate_password_hash('password')
    sql = "INSERT INTO `user`(`email`, `password_hash`, `created`, `permission`, `updated`) " \
              "VALUES ('syllahub@gmail.com','{}',CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP) " \
              "ON DUPLICATE KEY UPDATE `permission`='admin'".format(sa.text(password_hash))
    #print(sql)
    op.execute(sql)    

    #op.execute(
    #    "INSERT INTO `user`(`email`, `password_hash`, `created`, `permission`, `updated`) "
    #    "VALUES ('admin4@syllahub.com',sa.text(password_hash),CURRENT_TIMESTAMP,'admin',CURRENT_TIMESTAMP) "
    #        "ON DUPLICATE KEY UPDATE `permission`='admin'")    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # No downgrade needed. 
    pass
    # ### end Alembic commands ###
