"""drop syllabus table

Revision ID: 36718059f24d
Revises: 0eb4a8b6b715
Create Date: 2019-03-22 00:52:12.762733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36718059f24d'
down_revision = '0eb4a8b6b715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('syllabus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syllabus',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('section', sa.Integer(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', 'section', 'version')
    )

    # ### end Alembic commands ###
