""" edit course primary key

Revision ID: 45e747936772
Revises: 239ae4d7d3f4
Create Date: 2019-03-22 01:49:00.225962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45e747936772'
down_revision = '239ae4d7d3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('PRIMARY', 'course', type_='primary')
    op.drop_column('course', 'id')
    op.create_primary_key('pk_course', 'course', ['number', 'version'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('PRIMARY', 'course', type_='primary')
    op.add_column('course', sa.Column('id', sa.Integer(), nullable=False))
    op.create_primary_key('pk_course', 'course', ['id', 'version'])
    # ### end Alembic commands ###
