"""edit users table

Revision ID: 5227cc04a220
Revises: a10250763f6a
Create Date: 2019-03-31 20:40:41.339115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5227cc04a220'
down_revision = 'a10250763f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 
                    'email',
                    existing_type=mysql.VARCHAR(length=120),
                    nullable=False)
    
    op.alter_column('user', 
                    'password_hash',
                    existing_type=mysql.VARCHAR(length=128),
                    nullable=False)
    
    op.alter_column('user', 
                    'username',
                    existing_type=mysql.VARCHAR(length=64),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 
                    'username',
                    existing_type=mysql.VARCHAR(length=64),
                    nullable=True)
    
    op.alter_column('user', 
                    'password_hash',
                    existing_type=mysql.VARCHAR(length=128),
                    nullable=True)
    
    op.alter_column('user', 
                    'email',
                    existing_type=mysql.VARCHAR(length=120),
                    nullable=True)
    # ### end Alembic commands ###
