"""edit course fields

Revision ID: 6133a336641e
Revises: 6e070ac5b5b8
Create Date: 2019-03-22 00:48:02.929541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6133a336641e'
down_revision = '6e070ac5b5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('building', sa.String(length=70), nullable=True))
    op.add_column('course', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('course', sa.Column('is_core', sa.Boolean(), nullable=True))
    op.add_column('course', sa.Column('is_diversity', sa.Boolean(), nullable=True))
    op.add_column('course', sa.Column('is_elr', sa.Boolean(), nullable=True))
    op.add_column('course', sa.Column('is_wi', sa.Boolean(), nullable=True))
    op.add_column('course', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('course', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('prerequisites', sa.String(length=256), nullable=True))
    op.add_column('course', sa.Column('room', sa.String(length=50), nullable=True))
    op.add_column('course', sa.Column('updated', sa.DateTime(), nullable=False))
    op.drop_column('course', 'crn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('crn', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('course', 'updated')
    op.drop_column('course', 'room')
    op.drop_column('course', 'prerequisites')
    op.drop_column('course', 'number')
    op.drop_column('course', 'name')
    op.drop_column('course', 'is_wi')
    op.drop_column('course', 'is_elr')
    op.drop_column('course', 'is_diversity')
    op.drop_column('course', 'is_core')
    op.drop_column('course', 'created')
    op.drop_column('course', 'building')
    # ### end Alembic commands ###
