"""update model instructor fks

Revision ID: 661647e76623
Revises: 48cfb9483352
Create Date: 2019-04-12 15:45:02.367107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661647e76623'
down_revision = '48cfb9483352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name='syllabus_instructor_ibfk_1', 
                       table_name='syllabus_instructor', 
                       type_='foreignkey')
    
    op.create_foreign_key(constraint_name='syllabus_instructor_ibfk_1',
                          source_table='syllabus_instructor', 
                          referent_table='instructor', 
                          local_cols=['instructor_id'], 
                          remote_cols=['id'], 
                          onupdate='CASCADE', 
                          ondelete='CASCADE')
    
    op.drop_constraint(constraint_name='syllabus_instructor_ibfk_2', 
                       table_name='syllabus_instructor', 
                       type_='foreignkey')

    op.create_foreign_key(constraint_name='syllabus_instructor_ibfk_2', 
                          source_table='syllabus_instructor', 
                          referent_table='syllabus', 
                          local_cols=[
                              'syllabus_section', 
                              'syllabus_semester', 
                              'syllabus_year', 
                              'syllabus_version', 
                              'syllabus_course_number', 
                              'syllabus_course_version',
                          ], 
                          remote_cols=[
                              'section', 
                              'semester', 
                              'year', 
                              'version', 
                              'course_number', 
                              'course_version',
                          ],
                          onupdate='CASCADE', 
                          ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name='syllabus_instructor_ibfk_1', 
                       table_name='syllabus_instructor', 
                       type_='foreignkey') 

    op.create_foreign_key(constraint_name='syllabus_instructor_ibfk_1',
                          source_table='syllabus_instructor', 
                          referent_table='instructor', 
                          local_cols=['instructor_id'], 
                          remote_cols=['id'])
    
    op.drop_constraint(constraint_name='syllabus_instructor_ibfk_2', 
                       table_name='syllabus_instructor', 
                       type_='foreignkey')

    op.create_foreign_key(constraint_name='syllabus_instructor_ibfk_2', 
                          source_table='syllabus_instructor', 
                          referent_table='syllabus', 
                          local_cols=[
                              'syllabus_section', 
                              'syllabus_semester', 
                              'syllabus_year', 
                              'syllabus_version', 
                              'syllabus_course_number', 
                              'syllabus_course_version',
                          ], 
                          remote_cols=[
                              'section', 
                              'semester', 
                              'year', 
                              'version', 
                              'course_number', 
                              'course_version',
                          ])

    # ### end Alembic commands ###
