"""create fk user instructor

Revision ID: a10250763f6a
Revises: 1e93571e66b0
Create Date: 2019-03-31 20:17:26.774306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a10250763f6a'
down_revision = '1e93571e66b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('instructor_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_instructor', 'user', 'instructor', ['instructor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_instructor', 'user', type_='foreignkey')
    op.drop_column('user', 'instructor_id')
    # ### end Alembic commands ###
