"""drop table clo

Revision ID: b26218144c13
Revises: c441652403c7
Create Date: 2019-03-22 00:43:14.950208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b26218144c13'
down_revision = 'c441652403c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CLO')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CLO',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True,
                  nullable=False),
        sa.Column('description', mysql.VARCHAR(length=256), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
