"""update USER fk

Revision ID: be1c8e33b37e
Revises: 8a7f46ebafc8
Create Date: 2019-04-12 16:29:41.456675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1c8e33b37e'
down_revision = '8a7f46ebafc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(constraint_name='fk_user_instructor', 
                       table_name='user', 
                       type_='foreignkey')

    op.create_foreign_key(constraint_name='fk_user_instructor',
                          source_table='user', 
                          referent_table='instructor', 
                          local_cols=['instructor_id'], 
                          remote_cols=['id'], 
                          onupdate='CASCADE', 
                          ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name='fk_user_instructor', 
                       table_name='user', 
                       type_='foreignkey')

    op.create_foreign_key(constraint_name='fk_user_instructor',
                          source_table='user', 
                          referent_table='instructor', 
                          local_cols=['instructor_id'], 
                          remote_cols=['id'])
    # ### end Alembic commands ###
