"""create course clo

Revision ID: c14f264c92ba
Revises: eb030f05bfa2
Create Date: 2019-03-31 18:58:19.942602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c14f264c92ba'
down_revision = 'eb030f05bfa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_clo',
        sa.Column('course_number',  sa.Integer(), nullable=False),
        sa.Column('course_version', sa.Integer(), nullable=False),
        sa.Column('clo_id',         sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('course_number', 'course_version', 'clo_id'),
        sa.ForeignKeyConstraint(['clo_id'], ['clo.id'], ),
        sa.ForeignKeyConstraint(['course_number', 'course_version'], 
                                ['course.number', 'course.version'], ),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_clo')
    # ### end Alembic commands ###
