"""create tables

Revision ID: c68d32b90c8d
Revises: 19d5bf5471e2
Create Date: 2019-03-06 13:17:11.112292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68d32b90c8d'
down_revision = '19d5bf5471e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'CLO',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint('id'),)
   
    op.create_table(
        'course',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('crn', sa.Integer(), nullable=True),
        sa.Column('description', sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint('id', 'version'))
    
    op.create_table(
        'instructor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('phone', sa.Integer(), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint('id'))
    
    op.create_index(op.f('ix_instructor_email'), 'instructor', ['email'], 
                    unique=True)
    op.create_index(op.f('ix_instructor_name'), 'instructor', ['name'], 
                    unique=False)
    
    op.create_table(
        'syllabus',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('section', sa.Integer(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', 'section', 'version'))
    
    op.create_table('syllabus_static_info',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', 'version'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('syllabus_static_info')
    op.drop_table('syllabus')
    op.drop_index(op.f('ix_instructor_name'), table_name='instructor')
    op.drop_index(op.f('ix_instructor_email'), table_name='instructor')
    op.drop_table('instructor')
    op.drop_table('course')
    op.drop_table('CLO')
    # ### end Alembic commands ###
