"""empty message

Revision ID: c70e5b503515
Revises: 48cfb9483352
Create Date: 2019-04-09 13:40:13.048662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70e5b503515'
down_revision = '48cfb9483352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_course_syllabus', 'syllabus', type_='foreignkey')
    op.drop_constraint('syllabus_instructor_ibfk_2', 'syllabus_instructor', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('syllabus_instructor_ibfk_2', 'syllabus_instructor', 'syllabus', ['syllabus_section', 'syllabus_semester', 'syllabus_year', 'syllabus_version', 'syllabus_course_number', 'syllabus_course_version'], ['section', 'semester', 'year', 'version', 'course_number', 'course_version'])
    op.create_foreign_key('fk_course_syllabus', 'syllabus', 'course', ['course_number', 'course_version'], ['number', 'version'])
    # ### end Alembic commands ###
