"""create foreign key for course and syllabus


Revision ID: eb030f05bfa2
Revises: 45e747936772
Create Date: 2019-03-22 02:38:26.178770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb030f05bfa2'
down_revision = '45e747936772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("fk_course_syllabus",            #constraint_name, 
                          "syllabus",                      #source_table, 
                          "course",                        #referent_table, 
                          ['course_number', 'course_version'], #local_cols, 
                          ['number', 'version'], #remote_cols, 
                          )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_course_syllabus', 'syllabus', type_='foreignkey')
    print('no need to drop this time')
    # ### end Alembic commands ###
