"""create foreign key for course and syllabus


Revision ID: eb030f05bfa2
Revises: 45e747936772
Create Date: 2019-03-22 02:38:26.178770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb030f05bfa2'
down_revision = '45e747936772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(constraint_name='fk_course_syllabus',
                          source_table='syllabus', 
                          referent_table='course', 
                          local_cols=['course_number', 'course_version'], 
                          remote_cols=['number', 'version'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name='fk_course_syllabus', 
                       table_name='syllabus', 
                       type_='foreignkey')
    # ### end Alembic commands ###
